package com.invectorate.open.queutures;

/**
 * A {@link Queuture} that can itself be executed as a {@link Runnable}.
 * <p>
 * Running this object will result in this object's computation being executed in the current thread.
 * 
 * @author Noah Fontes <nfontes@invectorate.com>
 * 
 * @param <V>
 *            The type of object being generated by the computation.
 */
public interface RunnableQueuture<V> extends Runnable, Queuture<V> {}
